version: 2.1

orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      - cypress/run
    triggers:
      - schedule:
          cron: "0 0 * * MON"
          filters:
            branches:
              only:
                - master
                - beta

