version: 2.1

orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      - cypress/run:
          command: npx cypress run --spec "/root/project/cypress/integration/neutrogena.spec.js"
      
